// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clhdyrpzzazzujoulgvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsaGR5cnB6emF6enVqb3VsZ3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTg2OTIsImV4cCI6MjA3MDc3NDY5Mn0.cy21ig8Y0SC-qqBM0_a-1J1yNYRuotZqZc5C1nbyKkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});